// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package listener

import (
	"context"

	"github.com/actions/scaleset"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteMessage provides a mock function for the type MockClient
func (_mock *MockClient) DeleteMessage(ctx context.Context, messageID int) error {
	ret := _mock.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, messageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockClient_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID int
func (_e *MockClient_Expecter) DeleteMessage(ctx interface{}, messageID interface{}) *MockClient_DeleteMessage_Call {
	return &MockClient_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, messageID)}
}

func (_c *MockClient_DeleteMessage_Call) Run(run func(ctx context.Context, messageID int)) *MockClient_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DeleteMessage_Call) Return(err error) *MockClient_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, messageID int) error) *MockClient_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function for the type MockClient
func (_mock *MockClient) GetMessage(ctx context.Context, lastMessageID int, maxCapacity int) (*scaleset.RunnerScaleSetMessage, error) {
	ret := _mock.Called(ctx, lastMessageID, maxCapacity)

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 *scaleset.RunnerScaleSetMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*scaleset.RunnerScaleSetMessage, error)); ok {
		return returnFunc(ctx, lastMessageID, maxCapacity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *scaleset.RunnerScaleSetMessage); ok {
		r0 = returnFunc(ctx, lastMessageID, maxCapacity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*scaleset.RunnerScaleSetMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, lastMessageID, maxCapacity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type MockClient_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - lastMessageID int
//   - maxCapacity int
func (_e *MockClient_Expecter) GetMessage(ctx interface{}, lastMessageID interface{}, maxCapacity interface{}) *MockClient_GetMessage_Call {
	return &MockClient_GetMessage_Call{Call: _e.mock.On("GetMessage", ctx, lastMessageID, maxCapacity)}
}

func (_c *MockClient_GetMessage_Call) Run(run func(ctx context.Context, lastMessageID int, maxCapacity int)) *MockClient_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetMessage_Call) Return(runnerScaleSetMessage *scaleset.RunnerScaleSetMessage, err error) *MockClient_GetMessage_Call {
	_c.Call.Return(runnerScaleSetMessage, err)
	return _c
}

func (_c *MockClient_GetMessage_Call) RunAndReturn(run func(ctx context.Context, lastMessageID int, maxCapacity int) (*scaleset.RunnerScaleSetMessage, error)) *MockClient_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Session provides a mock function for the type MockClient
func (_mock *MockClient) Session() scaleset.RunnerScaleSetSession {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 scaleset.RunnerScaleSetSession
	if returnFunc, ok := ret.Get(0).(func() scaleset.RunnerScaleSetSession); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(scaleset.RunnerScaleSetSession)
	}
	return r0
}

// MockClient_Session_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Session'
type MockClient_Session_Call struct {
	*mock.Call
}

// Session is a helper method to define mock.On call
func (_e *MockClient_Expecter) Session() *MockClient_Session_Call {
	return &MockClient_Session_Call{Call: _e.mock.On("Session")}
}

func (_c *MockClient_Session_Call) Run(run func()) *MockClient_Session_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Session_Call) Return(runnerScaleSetSession scaleset.RunnerScaleSetSession) *MockClient_Session_Call {
	_c.Call.Return(runnerScaleSetSession)
	return _c
}

func (_c *MockClient_Session_Call) RunAndReturn(run func() scaleset.RunnerScaleSetSession) *MockClient_Session_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsRecorder creates a new instance of MockMetricsRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRecorder {
	mock := &MockMetricsRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsRecorder is an autogenerated mock type for the MetricsRecorder type
type MockMetricsRecorder struct {
	mock.Mock
}

type MockMetricsRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRecorder) EXPECT() *MockMetricsRecorder_Expecter {
	return &MockMetricsRecorder_Expecter{mock: &_m.Mock}
}

// RecordJobCompleted provides a mock function for the type MockMetricsRecorder
func (_mock *MockMetricsRecorder) RecordJobCompleted(msg *scaleset.JobCompleted) {
	_mock.Called(msg)
	return
}

// MockMetricsRecorder_RecordJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobCompleted'
type MockMetricsRecorder_RecordJobCompleted_Call struct {
	*mock.Call
}

// RecordJobCompleted is a helper method to define mock.On call
//   - msg *scaleset.JobCompleted
func (_e *MockMetricsRecorder_Expecter) RecordJobCompleted(msg interface{}) *MockMetricsRecorder_RecordJobCompleted_Call {
	return &MockMetricsRecorder_RecordJobCompleted_Call{Call: _e.mock.On("RecordJobCompleted", msg)}
}

func (_c *MockMetricsRecorder_RecordJobCompleted_Call) Run(run func(msg *scaleset.JobCompleted)) *MockMetricsRecorder_RecordJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobCompleted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobCompleted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRecorder_RecordJobCompleted_Call) Return() *MockMetricsRecorder_RecordJobCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsRecorder_RecordJobCompleted_Call) RunAndReturn(run func(msg *scaleset.JobCompleted)) *MockMetricsRecorder_RecordJobCompleted_Call {
	_c.Run(run)
	return _c
}

// RecordJobStarted provides a mock function for the type MockMetricsRecorder
func (_mock *MockMetricsRecorder) RecordJobStarted(msg *scaleset.JobStarted) {
	_mock.Called(msg)
	return
}

// MockMetricsRecorder_RecordJobStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobStarted'
type MockMetricsRecorder_RecordJobStarted_Call struct {
	*mock.Call
}

// RecordJobStarted is a helper method to define mock.On call
//   - msg *scaleset.JobStarted
func (_e *MockMetricsRecorder_Expecter) RecordJobStarted(msg interface{}) *MockMetricsRecorder_RecordJobStarted_Call {
	return &MockMetricsRecorder_RecordJobStarted_Call{Call: _e.mock.On("RecordJobStarted", msg)}
}

func (_c *MockMetricsRecorder_RecordJobStarted_Call) Run(run func(msg *scaleset.JobStarted)) *MockMetricsRecorder_RecordJobStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobStarted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobStarted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRecorder_RecordJobStarted_Call) Return() *MockMetricsRecorder_RecordJobStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsRecorder_RecordJobStarted_Call) RunAndReturn(run func(msg *scaleset.JobStarted)) *MockMetricsRecorder_RecordJobStarted_Call {
	_c.Run(run)
	return _c
}

// RecordStatistics provides a mock function for the type MockMetricsRecorder
func (_mock *MockMetricsRecorder) RecordStatistics(statistics *scaleset.RunnerScaleSetStatistic) {
	_mock.Called(statistics)
	return
}

// MockMetricsRecorder_RecordStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatistics'
type MockMetricsRecorder_RecordStatistics_Call struct {
	*mock.Call
}

// RecordStatistics is a helper method to define mock.On call
//   - statistics *scaleset.RunnerScaleSetStatistic
func (_e *MockMetricsRecorder_Expecter) RecordStatistics(statistics interface{}) *MockMetricsRecorder_RecordStatistics_Call {
	return &MockMetricsRecorder_RecordStatistics_Call{Call: _e.mock.On("RecordStatistics", statistics)}
}

func (_c *MockMetricsRecorder_RecordStatistics_Call) Run(run func(statistics *scaleset.RunnerScaleSetStatistic)) *MockMetricsRecorder_RecordStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.RunnerScaleSetStatistic
		if args[0] != nil {
			arg0 = args[0].(*scaleset.RunnerScaleSetStatistic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRecorder_RecordStatistics_Call) Return() *MockMetricsRecorder_RecordStatistics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsRecorder_RecordStatistics_Call) RunAndReturn(run func(statistics *scaleset.RunnerScaleSetStatistic)) *MockMetricsRecorder_RecordStatistics_Call {
	_c.Run(run)
	return _c
}

// RecordhDesiredRunners provides a mock function for the type MockMetricsRecorder
func (_mock *MockMetricsRecorder) RecordhDesiredRunners(count int) {
	_mock.Called(count)
	return
}

// MockMetricsRecorder_RecordhDesiredRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordhDesiredRunners'
type MockMetricsRecorder_RecordhDesiredRunners_Call struct {
	*mock.Call
}

// RecordhDesiredRunners is a helper method to define mock.On call
//   - count int
func (_e *MockMetricsRecorder_Expecter) RecordhDesiredRunners(count interface{}) *MockMetricsRecorder_RecordhDesiredRunners_Call {
	return &MockMetricsRecorder_RecordhDesiredRunners_Call{Call: _e.mock.On("RecordhDesiredRunners", count)}
}

func (_c *MockMetricsRecorder_RecordhDesiredRunners_Call) Run(run func(count int)) *MockMetricsRecorder_RecordhDesiredRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsRecorder_RecordhDesiredRunners_Call) Return() *MockMetricsRecorder_RecordhDesiredRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsRecorder_RecordhDesiredRunners_Call) RunAndReturn(run func(count int)) *MockMetricsRecorder_RecordhDesiredRunners_Call {
	_c.Run(run)
	return _c
}

// NewMockScaler creates a new instance of MockScaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScaler {
	mock := &MockScaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScaler is an autogenerated mock type for the Scaler type
type MockScaler struct {
	mock.Mock
}

type MockScaler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScaler) EXPECT() *MockScaler_Expecter {
	return &MockScaler_Expecter{mock: &_m.Mock}
}

// HandleDesiredRunnerCount provides a mock function for the type MockScaler
func (_mock *MockScaler) HandleDesiredRunnerCount(ctx context.Context, count int) (int, error) {
	ret := _mock.Called(ctx, count)

	if len(ret) == 0 {
		panic("no return value specified for HandleDesiredRunnerCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, count)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScaler_HandleDesiredRunnerCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleDesiredRunnerCount'
type MockScaler_HandleDesiredRunnerCount_Call struct {
	*mock.Call
}

// HandleDesiredRunnerCount is a helper method to define mock.On call
//   - ctx context.Context
//   - count int
func (_e *MockScaler_Expecter) HandleDesiredRunnerCount(ctx interface{}, count interface{}) *MockScaler_HandleDesiredRunnerCount_Call {
	return &MockScaler_HandleDesiredRunnerCount_Call{Call: _e.mock.On("HandleDesiredRunnerCount", ctx, count)}
}

func (_c *MockScaler_HandleDesiredRunnerCount_Call) Run(run func(ctx context.Context, count int)) *MockScaler_HandleDesiredRunnerCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScaler_HandleDesiredRunnerCount_Call) Return(n int, err error) *MockScaler_HandleDesiredRunnerCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockScaler_HandleDesiredRunnerCount_Call) RunAndReturn(run func(ctx context.Context, count int) (int, error)) *MockScaler_HandleDesiredRunnerCount_Call {
	_c.Call.Return(run)
	return _c
}

// HandleJobCompleted provides a mock function for the type MockScaler
func (_mock *MockScaler) HandleJobCompleted(ctx context.Context, jobInfo *scaleset.JobCompleted) error {
	ret := _mock.Called(ctx, jobInfo)

	if len(ret) == 0 {
		panic("no return value specified for HandleJobCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *scaleset.JobCompleted) error); ok {
		r0 = returnFunc(ctx, jobInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScaler_HandleJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleJobCompleted'
type MockScaler_HandleJobCompleted_Call struct {
	*mock.Call
}

// HandleJobCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - jobInfo *scaleset.JobCompleted
func (_e *MockScaler_Expecter) HandleJobCompleted(ctx interface{}, jobInfo interface{}) *MockScaler_HandleJobCompleted_Call {
	return &MockScaler_HandleJobCompleted_Call{Call: _e.mock.On("HandleJobCompleted", ctx, jobInfo)}
}

func (_c *MockScaler_HandleJobCompleted_Call) Run(run func(ctx context.Context, jobInfo *scaleset.JobCompleted)) *MockScaler_HandleJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *scaleset.JobCompleted
		if args[1] != nil {
			arg1 = args[1].(*scaleset.JobCompleted)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScaler_HandleJobCompleted_Call) Return(err error) *MockScaler_HandleJobCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScaler_HandleJobCompleted_Call) RunAndReturn(run func(ctx context.Context, jobInfo *scaleset.JobCompleted) error) *MockScaler_HandleJobCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// HandleJobStarted provides a mock function for the type MockScaler
func (_mock *MockScaler) HandleJobStarted(ctx context.Context, jobInfo *scaleset.JobStarted) error {
	ret := _mock.Called(ctx, jobInfo)

	if len(ret) == 0 {
		panic("no return value specified for HandleJobStarted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *scaleset.JobStarted) error); ok {
		r0 = returnFunc(ctx, jobInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScaler_HandleJobStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleJobStarted'
type MockScaler_HandleJobStarted_Call struct {
	*mock.Call
}

// HandleJobStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - jobInfo *scaleset.JobStarted
func (_e *MockScaler_Expecter) HandleJobStarted(ctx interface{}, jobInfo interface{}) *MockScaler_HandleJobStarted_Call {
	return &MockScaler_HandleJobStarted_Call{Call: _e.mock.On("HandleJobStarted", ctx, jobInfo)}
}

func (_c *MockScaler_HandleJobStarted_Call) Run(run func(ctx context.Context, jobInfo *scaleset.JobStarted)) *MockScaler_HandleJobStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *scaleset.JobStarted
		if args[1] != nil {
			arg1 = args[1].(*scaleset.JobStarted)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScaler_HandleJobStarted_Call) Return(err error) *MockScaler_HandleJobStarted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScaler_HandleJobStarted_Call) RunAndReturn(run func(ctx context.Context, jobInfo *scaleset.JobStarted) error) *MockScaler_HandleJobStarted_Call {
	_c.Call.Return(run)
	return _c
}
