package main

import (
	"os"
	"os/exec"
	"strings"
	"text/template"
)

func main() {
	sha, err := exec.Command("git", "rev-parse", "HEAD").Output()
	if err != nil {
		panic(err)
	}

	// get latest tag
	version := "NA"
	if output, err := exec.Command("git", "describe", "--tags", "--abbrev=0").Output(); err == nil {
		version = string(output)
	}

	f, err := os.OpenFile("build.go", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	err = tmpl.Execute(f, struct {
		SHA     string
		Version string
	}{
		SHA:     strings.TrimSpace(string(sha)),
		Version: version,
	})
	if err != nil {
		panic(err)
	}
}

var tmpl = template.Must(template.New("build.go").Parse(`// Code generated by build.go; DO NOT EDIT.

package scaleset

const (
	commitSHA = "{{- .SHA -}}"
	packageVersion   = "{{- .Version -}}"
)
`),
)
